// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUsuN3gg25Mmrf8_rdXzXyTo6oQ8jPnQg',
    appId: '1:95331269802:web:0f681074a254a799d724d3',
    messagingSenderId: '95331269802',
    projectId: 'foodie-54513',
    authDomain: 'foodie-54513.firebaseapp.com',
    storageBucket: 'foodie-54513.firebasestorage.app',
    measurementId: 'G-TNX4LSVL9Y',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYzS7ecCjXscZ0QOqjeR7qu2E4HIjwOUs',
    appId: '1:95331269802:ios:53dfea9341db4318d724d3',
    messagingSenderId: '95331269802',
    projectId: 'foodie-54513',
    storageBucket: 'foodie-54513.firebasestorage.app',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYzS7ecCjXscZ0QOqjeR7qu2E4HIjwOUs',
    appId: '1:95331269802:ios:53dfea9341db4318d724d3',
    messagingSenderId: '95331269802',
    projectId: 'foodie-54513',
    storageBucket: 'foodie-54513.firebasestorage.app',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUsuN3gg25Mmrf8_rdXzXyTo6oQ8jPnQg',
    appId: '1:95331269802:web:c571e3a42b20b599d724d3',
    messagingSenderId: '95331269802',
    projectId: 'foodie-54513',
    authDomain: 'foodie-54513.firebaseapp.com',
    storageBucket: 'foodie-54513.firebasestorage.app',
    measurementId: 'G-JHM8SWSF3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtv7HWZi4dpRdFxZs3m8FnJx56fo8B1kQ',
    appId: '1:95331269802:android:c73c3439d590df8ad724d3',
    messagingSenderId: '95331269802',
    projectId: 'foodie-54513',
    storageBucket: 'foodie-54513.firebasestorage.app',
  );

}